// SPDX-License-Identifier: Apache-2.0
// AUTO-GENERATED by scripts/generate-fixture.ts - do not edit.
// Source: C:/Users/helpy/AppData/Local/Temp/hype-fix.json
// Generated at: 2026-09-24T16:48:51.925Z

pragma solidity 0.8.26;

import {HyperCoreTypes} from "../../src/types.sol";
import {SnapshotInput} from "../../src/HyperCoreSnapshotMock.sol";

/**
 * @dev Frozen market snapshot for HyperCoreSnapshotMock.
 *
 * Use this in a test setUp():
 *
 *     HyperCoreSnapshotMock snap =
 *         new HyperCoreSnapshotMock(
 *             Fixture.candles(), Fixture.funding(), Fixture.market()
 *         );
 *
 * Snapshot: 2 candles, 2 funding ticks, 1 market data.
 */
library Fixture {

    function candles() external pure returns (SnapshotInput.CandleEntry[] memory)
    {
        SnapshotInput.CandleEntry[] memory arr = new SnapshotInput.CandleEntry[](2);
        arr[0] = SnapshotInput.CandleEntry({
    coin: "HYPE",
    interval: "1h",
    candle: HyperCoreTypes.Candle({
        open: 99995000,
        high: 100005000,
        low: 99990000,
        close: 100000000,
        startTime: 1700000000,
        endTime: 1700003600,
        volume: 1000000
    })
});
        arr[1] = SnapshotInput.CandleEntry({
    coin: "HYPE",
    interval: "1h",
    candle: HyperCoreTypes.Candle({
        open: 100000000,
        high: 100010000,
        low: 99995000,
        close: 100005000,
        startTime: 1700003600,
        endTime: 1700007200,
        volume: 1500000
    })
});
        return arr;
    }

    function funding() external pure returns (SnapshotInput.FundingEntry[] memory)
    {
        SnapshotInput.FundingEntry[] memory arr = new SnapshotInput.FundingEntry[](2);
        arr[0] = SnapshotInput.FundingEntry({
    coin: "HYPE",
    tick: HyperCoreTypes.FundingSnapshot({
        fundingRate: 5000,
        oi: 1000000,
        timestamp: 1700003600
    })
});
        arr[1] = SnapshotInput.FundingEntry({
    coin: "HYPE",
    tick: HyperCoreTypes.FundingSnapshot({
        fundingRate: 6000,
        oi: 1200000,
        timestamp: 1700007200
    })
});
        return arr;
    }

    function market() external pure returns (SnapshotInput.MarketEntry[] memory)
    {
        SnapshotInput.MarketEntry[] memory arr = new SnapshotInput.MarketEntry[](1);
        arr[0] = SnapshotInput.MarketEntry({
    coin: "HYPE",
    data: HyperCoreTypes.MarketData({
        spotPrice: 100005000,
        oraclePrice: 100005500,
        timestamp: 1700003600
    })
});
        return arr;
    }
}
